import { NextRequest, NextResponse } from "next/server";
import { createChatFan, deleteChatFan, listChatFans, requireChatAdminCapability, requireChatAdminFanRuntime, updateChatFan } from "@/lib/chatAdmin";
import { assertChatAdminFanInput, ChatAdminPolicyError } from "@/lib/chatAdminPolicy.mjs";
import { isTrustedFanMindMutationRequest, readBoundedJsonRequest } from "@/lib/httpMutationPolicy.mjs";
import { WorkspaceAuthorizationError } from "@/lib/workspaceAuthorization";
const denied=(error:unknown)=>NextResponse.json({error:error instanceof WorkspaceAuthorizationError?error.code:"chat_admin_unavailable"},{status:error instanceof WorkspaceAuthorizationError?(error.code==="unauthenticated"?401:403):503});
const PAGE_SIZE=50,UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu;
export async function GET(request:NextRequest){try{requireChatAdminFanRuntime();const {workspace}=await requireChatAdminCapability();const characterId=request.nextUrl.searchParams.get("character_id"),cursor=request.nextUrl.searchParams.get("cursor")??"0",offset=Number(cursor);if(!characterId||!/^\d+$/u.test(cursor)||!Number.isSafeInteger(offset)||offset<0)return NextResponse.json({error:"invalid_character"},{status:400});const rows=await listChatFans(workspace.id,characterId,offset,PAGE_SIZE+1);return NextResponse.json({fans:rows.slice(0,PAGE_SIZE),next_cursor:rows.length>PAGE_SIZE?String(offset+PAGE_SIZE):null});}catch(error){return denied(error)}}
export async function POST(request:NextRequest){if(!isTrustedFanMindMutationRequest(request))return NextResponse.json({error:"untrusted_origin"},{status:403});try{requireChatAdminFanRuntime();const {workspace}=await requireChatAdminCapability();const parsed=await readBoundedJsonRequest(request,20_000);if(!parsed.ok||!parsed.value||typeof parsed.value!=="object")return NextResponse.json({error:"invalid_body"},{status:400});const body=parsed.value as Record<string,unknown>;if(typeof body.character_id!=="string"||typeof body.creation_id!=="string"||!UUID.test(body.creation_id))return NextResponse.json({error:"invalid_character"},{status:400});return NextResponse.json({fan:await createChatFan(workspace.id,body.character_id,body.creation_id,assertChatAdminFanInput(body))},{status:201});}catch(error){if(error instanceof ChatAdminPolicyError)return NextResponse.json({error:error.code},{status:400});return denied(error)}}
export async function PATCH(request:NextRequest){if(!isTrustedFanMindMutationRequest(request))return NextResponse.json({error:"untrusted_origin"},{status:403});try{requireChatAdminFanRuntime();const {workspace}=await requireChatAdminCapability();const parsed=await readBoundedJsonRequest(request,20_000);if(!parsed.ok||!parsed.value||typeof parsed.value!=="object")return NextResponse.json({error:"invalid_body"},{status:400});const body=parsed.value as Record<string,unknown>;if(typeof body.character_id!=="string"||typeof body.id!=="string"||!Number.isInteger(body.revision))return NextResponse.json({error:"invalid_fan"},{status:400});return NextResponse.json({fan:await updateChatFan(workspace.id,body.character_id,body.id,body.revision as number,assertChatAdminFanInput(body))});}catch(error){if(error instanceof ChatAdminPolicyError)return NextResponse.json({error:error.code},{status:400});return denied(error)}}
export async function DELETE(request:NextRequest){if(!isTrustedFanMindMutationRequest(request))return NextResponse.json({error:"untrusted_origin"},{status:403});try{requireChatAdminFanRuntime();const {workspace}=await requireChatAdminCapability();const parsed=await readBoundedJsonRequest(request,2_000);if(!parsed.ok||!parsed.value||typeof parsed.value!=="object")return NextResponse.json({error:"invalid_body"},{status:400});const body=parsed.value as Record<string,unknown>;if(typeof body.character_id!=="string"||typeof body.id!=="string"||!Number.isInteger(body.revision))return NextResponse.json({error:"invalid_fan"},{status:400});await deleteChatFan(workspace.id,body.character_id,body.id,body.revision as number);return new Response(null,{status:204});}catch(error){return denied(error)}}
