export const landingEnglishCopy: Record<string, string> = {
  "FanMind | KI-CRM für Creator, Clubs und Events": "FanMind | AI CRM for creators, clubs and events",
  "Dein KI-gestütztes": "Your AI-powered",
  "Fan-CRM für Nachrichten, Erinnerungen": "Fan CRM for messages and reminders",
  "FanMind bündelt Kontakte, Gesprächskontext und KI-Antwortvorschläge in einem manuellen Workflow. Du prüfst, kopierst und sendest selbst – ohne automatische Sendefunktion.": "FanMind brings contacts, conversation context and AI reply suggestions together in a manual workflow. You review, copy and send them yourself – with no automatic sending.",
  "Kontakte / Fans": "Contacts / fans",
  "Profile, Gesprächsnotizen, Tags und Kontaktverlauf werden zentral und nachvollziehbar gepflegt.": "Profiles, conversation notes, tags and contact history are maintained centrally and transparently.",
  "FanMind erstellt passende Entwürfe aus Kontext und Kontaktwissen. Du prüfst, kopierst und sendest selbst.": "FanMind creates suitable drafts from context and contact knowledge. You review, copy and send them yourself.",
  "Bestehende Kontakte importieren, Details speichern und Follow-ups aus dem Kontext vorbereiten.": "Import existing contacts, save details and prepare follow-ups from context.",
  "Manuelle Follow-ups": "Manual follow-ups",
  "Nächste Schritte bleiben sichtbar, priorisiert und bewusst manuell steuerbar.": "Next steps remain visible, prioritized and deliberately controlled by a human.",
  "Kampagnen, Reichweiten-Analytics und Rollen/Rechte sind klar als spätere Ausbaustufen markiert.": "Campaigns, reach analytics and roles and permissions are clearly marked as later expansion stages.",
  "Keine automatische Sendefunktion, keine Bankdaten in FanMind und sichere Zahlung über den Zahlungsanbieter.": "No automatic sending, no bank details in FanMind and secure payment through the payment provider.",
  "Kostenlos testen": "Try for free",
  "Hilfe & Support": "Help & support",
  "Klare nächste Schritte": "Clear next steps",
  "VIP · premium_interessiert · Letzter Kontakt: Heute, 09:42": "VIP · premium interest · Last contact: Today, 09:42",
  "Vorschlag: Early-Bird Zugang und 10 % Rabatt sind noch verfügbar.": "Suggestion: Early-bird access and a 10% discount are still available.",
  "VIP-Upgrade Infos · Heute, 10:00 · Feedback abfragen": "VIP upgrade information · Today, 10:00 · Ask for feedback",
  "Kampagnen als geprüfte Entwürfe vorbereiten – Versand bleibt aktuell inaktiv und manuell abgegrenzt.": "Prepare campaigns as reviewed drafts – sending remains inactive and manually separated.",
  "Sommer-Event Early Bird · Vorschau · manuelle Freigabe": "Summer event early bird · Preview · manual approval",
  "Produktvorschau für dein": "Product preview for your",
  "Fan-Management mit Beispieldaten.": "fan management with sample data.",
  "Beispieldaten": "Sample data",
  "Interessen: Sommer-Event, VIP-Angebote": "Interests: summer event, VIP offers",
  "Tonalität: freundlich, wertschätzend": "Tone: friendly and appreciative",
  "Letzter Kontakt: Heute, 09:42": "Last contact: Today, 09:42",
  "Als Member erhältst du 10 % Rabatt in den ersten 48 Stunden.": "Members receive a 10% discount during the first 48 hours.",
  "Danke für dein Interesse! Melde dich gerne bei weiteren Fragen.": "Thank you for your interest. Feel free to contact us with any further questions.",
  "Nächster Schritt: VIP-Infos + Friend-Ticket": "Next step: VIP information + friend ticket",
  "Manuelle Erinnerung: Heute, 10:00": "Manual reminder: Today, 10:00",
  "Priorität: Hoch": "Priority: High",
  "Roadmap: Segment- und Kampagnenplanung": "Roadmap: segment and campaign planning",
  "Versand: inaktiv / manuell abgegrenzt": "Sending: inactive / manually separated",
  "Follow-ups werden sichtbar, bevor Gespräche verloren gehen.": "Follow-ups become visible before conversations are lost.",
  "Demo-Workflow mit Beispieldaten": "Demo workflow with sample data",
  "ein nächster Schritt.": "a next step.",
  "Produktvorschau mit Beispieldaten: FanMind zeigt, wie Kontakte, Kontaktwissen, KI-Vorschläge und manuelle Follow-ups zusammenarbeiten.": "Product preview with sample data: FanMind shows how contacts, contact knowledge, AI suggestions and manual follow-ups work together.",
  "Demo-Ergebnis: klarer nächster Schritt, besseres Timing": "Demo result: a clear next step and better timing",
  "Beispieldaten zeigen den manuellen Workflow: Antwort vorbereiten, Follow-up planen und final selbst senden.": "Sample data shows the manual workflow: prepare a reply, plan a follow-up and send it yourself.",
  "FanMind denkt mit. Für echte Verbindungen und nachvollziehbare nächste Schritte.": "FanMind thinks with you. For genuine connections and transparent next steps.",
  "Jede Antwort nutzt Sandras Kontext und Kontaktwissen.": "Every reply uses Sandra's context and contact knowledge.",
  "Passende Vorschläge entstehen aus Sandras Verlauf und aktuellem Bedarf.": "Suitable suggestions are created from Sandra's history and current needs.",
  "Ordne deine wichtigsten": "Organize your most important",
  "Kanäle ehrlich ein.": "channels transparently.",
  "DM- und Profilkontext vorbereitet, noch keine Live-Anbindung.": "DM and profile context prepared; no live connection yet.",
  "Community- und Kommentar-Kontext für spätere Workflows.": "Community and comment context for later workflows.",
  "Chat-Kontext für spätere Synchronisation vorbereitet.": "Chat context prepared for later synchronization.",
  "Creator-Kontakte als späterer Social-Kanal.": "Creator contacts as a later social channel.",
  "Server- und Profilkontext vorbereitet, keine Live-Integration.": "Server and profile context prepared; no live integration.",
  "Anfragen manuell bündeln; Synchronisation bleibt vorbereitet.": "Bundle inquiries manually; synchronization remains prepared.",
  "Formularanfragen manuell übernehmen und zuordnen.": "Take over and assign form inquiries manually.",
  "Streaming-Community als späterer Kanal.": "Streaming community as a later channel.",
  "Live-Kommentare als späterer Pilot-Kanal.": "Live comments as a later pilot channel.",
  "Community-Kontext für spätere Pilotphasen.": "Community context for later pilot phases.",
  "Bewertungen für spätere Antwort-Workflows.": "Reviews for later reply workflows.",
  "Review-Kontext für spätere Bearbeitung.": "Review context for later processing.",
  "App-Feedback als späterer Review-Kanal.": "App feedback as a later review channel.",
  "Marketplace-Kontext für spätere Prüfung.": "Marketplace context for later review.",
  "Marketplace-Nachrichten für spätere Regionen.": "Marketplace messages for later regions.",
  "Kurzvideo-Kanal für spätere Marktprüfung.": "Short-video channel for later market review.",
  "Social-Profile für spätere internationale Piloten.": "Social profiles for later international pilots.",
  "Messaging-Kanal für spätere Marktprüfung.": "Messaging channel for later market review.",
  "Messenger-Kontext für spätere Pilotphasen.": "Messenger context for later pilot phases.",
  "Kommentare und Handles als geprüfter Roadmap-Kanal.": "Comments and handles as a reviewed roadmap channel.",
  "Seiten- und Profilkontakte vorbereitet, nicht produktiv angebunden.": "Page and profile contacts prepared, not connected in production.",
  "Community-Nachrichten als geplanter Kanal.": "Community messages as a planned channel.",
  "Business-Kontakte und Nachrichten für spätere Prüfung.": "Business contacts and messages for later review.",
  "Handles und Aktivität für spätere Einordnung.": "Handles and activity for later classification.",
  "Communities und Erwähnungen für spätere Pilotphasen.": "Communities and mentions for later pilot phases.",
  "Manuell / CSV": "Manual / CSV",
  "Kontakte importieren oder manuell pflegen.": "Import contacts or maintain them manually.",
  "Content-Interaktionen für spätere Auswertung.": "Content interactions for later analysis.",
  "Supporter-Kontext für spätere Workflows.": "Supporter context for later workflows.",
  "Newsletter-Reaktionen für spätere CRM-Sichten.": "Newsletter reactions for later CRM views.",
  "Shop-Kontakte als mögliche Commerce-Erweiterung.": "Shop contacts as a possible commerce extension.",
  "Kurzvideo-Community für spätere Prüfung.": "Short-video community for later review.",
  "Messaging-Kontext für spätere regionale Piloten.": "Messaging context for later regional pilots.",
  "Regionale Communities für spätere Validierung.": "Regional communities for later validation.",
  "Creator-Community für spätere Marktprüfung.": "Creator community for later market review.",
  "Kampagnen": "Campaigns",
  "Wachstumssignale einordnen.": "Classify growth signals.",
  "Aktiv / verfügbar": "Active / available",
  "Manuelle Kontaktpflege, CSV-Import, KI-Antwortvorschläge, Kontaktwissen, Follow-ups und Demo.": "Manual contact management, CSV import, AI reply suggestions, contact knowledge, follow-ups and demo.",
  "Facebook und Instagram werden nur als vorbereitete Beta-Workflows gezeigt; keine produktive Vollintegration.": "Facebook and Instagram are shown only as prepared beta workflows; there is no full production integration.",
  "WhatsApp, TikTok, X, Discord, Kampagnen, Analytics/Reichweite sowie Rollen/Rechte bleiben Roadmap.": "WhatsApp, TikTok, X, Discord, campaigns, analytics and reach, and roles and permissions remain on the roadmap.",
  "FanMind sendet nichts automatisch: KI bereitet vor, der Mensch prüft und sendet final selbst.": "FanMind sends nothing automatically: AI prepares, a human reviews and sends the final message.",
  "✓ Aktiv, Beta und Coming Soon klar getrennt": "✓ Active, beta and coming soon clearly separated",
  "Manuelle Fans": "Manual contacts",
  "Fan-Import & Datenqualität": "Contact import & data quality",
  "Technische & rechtliche Prüfung": "Technical & legal review",
  "Nächster Schritt": "Next step",
  "Produktions- und Testdaten trennen": "Separate production and test data",
  "Weitere Social-Kanäle": "Additional social channels",
  "Später": "Later",
  "LinkedIn & weitere Kanäle": "LinkedIn & additional channels",
  "CSV-Import für Segmente nutzen": "Use CSV import for segments",
  "Kampagnen-Vorbereitung": "Campaign preparation",
  "Geprüfte Kampagnen-Entwürfe": "Reviewed campaign drafts",
  "Manuelle Freigabe": "Manual approval",
  "Kein Auto-Senden": "No auto-sending",
  "Reichweiten-Auswertung": "Reach analysis",
  "Interaktionen und Wachstumssignale einordnen": "Classify interactions and growth signals",
  "Keine Vollanalytics als Live-Suite": "No full analytics as a live suite",
  "Teamzugänge": "Team access",
  "Automationen nur als geprüfte Erinnerungen": "Automations only as reviewed reminders",
  "Manuelle Freigabe vor Versand": "Manual approval before sending",
  "FanMind ist ein KI-gestützter Antwort- und Kontaktwissen-Assistent für Teams. Dieses Produkt konzentriert sich auf Kontakte, KI-Antwortvorschläge, Kontaktwissen, Follow-ups und CSV-Import.": "FanMind is an AI-assisted reply and contact knowledge assistant for teams. This product focuses on contacts, AI reply suggestions, contact knowledge, follow-ups and CSV import.",
  "Monatlich kündbar": "Cancel monthly",
  "Aktiv": "Active",
  "Für kleine Teams, die produktiv starten und flexibel bleiben möchten.": "For small teams that want to start productively and remain flexible.",
  "jederzeit zum Ende des bezahlten Monats kündbar": "cancel at any time at the end of the paid month",
  "Kontakte/Fans und manuelle Kontaktpflege": "Contacts/fans and manual contact management",
  "CSV-Import, Notizen und Kontaktwissen": "CSV import, notes and contact knowledge",
  "Kein automatischer Versand": "No automatic sending",
  "Für Teams, die FanMind langfristiger einführen und die Setup-Gebühr sparen möchten.": "For teams that want to introduce FanMind for the long term and save the setup fee.",
  "12 Monate Mindestlaufzeit · danach monatliche Verlängerung": "12-month minimum term · monthly renewal thereafter",
  "Setup ohne separate Setup-Gebühr": "Setup without a separate setup fee",
  "Kontakte/Fans, CSV-Import und Kontaktwissen": "Contacts/fans, CSV import and contact knowledge",
  "Roadmap-Paket für wachsende Teams, die mehrere Profile und mehr Struktur vorbereiten möchten.": "Roadmap package for growing teams that want to prepare multiple profiles and more structure.",
  "Basis-Segmente und Listen als Roadmap": "Basic segments and lists on the roadmap",
  "Reichweiten- und Performance-Signale als Roadmap": "Reach and performance signals on the roadmap",
  "Roadmap für Agenturen mit mehreren Kunden-Workspaces und abgestimmten Freigaben.": "Roadmap for agencies with multiple client workspaces and coordinated approvals.",
  "Team-Rollen und Rechte als Roadmap": "Team roles and permissions on the roadmap",
  "Kampagnen nur mit manueller Freigabe geplant": "Campaigns planned only with manual approval",
  "Für spätere individuelle Anforderungen, Governance und größere interne Abstimmungen.": "For later individual requirements, governance and larger internal coordination.",
  "Coming Soon · individuelle Prüfung erforderlich": "Coming soon · individual review required",
  "Individuelle Workflows später geplant": "Individual workflows planned for later",
  "Governance und Freigabeprozesse als Roadmap": "Governance and approval processes on the roadmap",
  "Keine Enterprise-Rollen in der aktuellen Version aktiv": "No enterprise roles are active in the current version",
  "Keine automatische Sendefunktion": "No automatic sending",
  "Technische und rechtliche Prüfung vor Zusage": "Technical and legal review before commitment",
  "Keine Fake-Live-Kennzahlen": "No fake live metrics",
  "Kontakt aufnehmen": "Contact us",
  "FanMind bereitet vor. Du entscheidest, kopierst und sendest selbst.": "FanMind prepares. You decide, copy and send yourself.",
  "Keine Bankdaten in FanMind": "No bank details in FanMind",
  "Zahlungen laufen sicher über den Zahlungsanbieter; FanMind speichert keine Bankdaten.": "Payments are processed securely by the payment provider; FanMind stores no bank details.",
  "Antwortvorschläge sind Hilfen, keine Pflichtantworten und kein Autopilot.": "Reply suggestions are aids, not mandatory replies and not an autopilot.",
  "Starter-Nettopreise, Laufzeiten sowie Steuer- oder Reverse-Charge-Behandlung werden transparent dargestellt.": "Starter net prices, terms, and the applicable tax or reverse-charge treatment are shown transparently.",
  "Einwilligungen und Opt-outs sollen transparent dokumentiert und für dein Team nachvollziehbar bleiben.": "Consents and opt-outs should be documented transparently and remain traceable for your team.",
  "Team-Zugriffe werden bewusst geplant – mit klaren Zuständigkeiten statt ungeprüfter Vollzugriffe.": "Team access is deliberately planned – with clear responsibilities instead of unchecked full access.",
  "Änderungen, Freigaben und sensible Aktionen sind als nachvollziehbare Protokollierung vorgesehen.": "Changes, approvals and sensitive actions are intended to be logged transparently.",
  "Präferenzen und Sperrlisten werden respektiert – für vertrauensvolle, bewusste Kommunikation.": "Preferences and blocklists are respected – for trustworthy, deliberate communication.",
  "KI-Vorschläge bleiben Vorschläge. Dein Team prüft bewusst, bevor etwas an Fans geht.": "AI suggestions remain suggestions. Your team reviews them deliberately before anything is sent to contacts.",
  "Datenschutz, Transparenz und europäische Anforderungen werden als Produktprinzip mitgedacht.": "Privacy, transparency and European requirements are considered product principles.",
  "Keine automatischen Nachrichten ohne Freigabe": "No automatic messages without approval",
  "Jede KI-Antwort bleibt ein geprüfter Entwurf.": "Every AI reply remains a reviewed draft.",
  "Sichere Workflows für Teams": "Secure workflows for teams",
  "Klare Prozesse, definierte Regeln und bewusste Zuständigkeiten.": "Clear processes, defined rules and deliberate responsibilities.",
  "E-Mails, Formulare und Gesprächsnotizen werden zentral gebündelt.": "Emails, forms and conversation notes are bundled centrally.",
  "Weniger Chaos, mehr Überblick": "Less chaos, more clarity",
  "FanMind bereitet passende Vorschläge vor – dein Team prüft und entscheidet.": "FanMind prepares suitable suggestions – your team reviews and decides.",
  "Datenschutz, Transparenz und bewusste Freigaben stehen im Fokus.": "Privacy, transparency and deliberate approvals are the focus.",
  "Kontakte, Follow-ups und Roadmap-Signale helfen dir, Wirkung besser einzuordnen.": "Contacts, follow-ups and roadmap signals help you assess impact more clearly.",
  "E-Mail, Kontakte, CSV-Import und zentrale Gesprächsnotizen stehen aktuell im Fokus. Weitere Kanäle wie WhatsApp, Social DMs und Community-Chats sind als Roadmap transparent markiert.": "Email, contacts, CSV import and central conversation notes are the current focus. Additional channels such as WhatsApp, social DMs and community chats are transparently marked as roadmap items.",
  "Schreib uns eine Nachricht zu deinem Use Case und zum passenden FanMind-Einstieg.": "Send us a message about your use case and the right way to start with FanMind.",
  "Sieh dir die Produktvorschau an und starte mit einem kostenlosen Demo-Zugang.": "View the product preview and start with free demo access.",
  "Login für bestehende Teams": "Login for existing teams",
  "Wir prüfen deinen Use Case und zeigen dir, wie FanMind in deinem Workflow eingesetzt werden kann.": "We review your use case and show you how FanMind can be used in your workflow.",
  "Persönliche Anfrage statt automatischem Newsletter.": "A personal inquiry instead of an automated newsletter.",
  "Copy-&-Open-Workflow · Keine automatische Sendefunktion": "Copy-and-open workflow · No automatic sending",
};
