import test from "node:test";import assert from "node:assert/strict";import {readFile} from "node:fs/promises";import {assertChatAdminCharacterInput,buildChatAdminCharacterContext} from "../src/lib/chatAdminPolicy.mjs";
const fixture={display_name:"Anna",profile_image_path:null,public_age:24,bio:"Vom User bereitgestellte Persona.",location:"Berlin",languages:["Deutsch"],personality:"direkt",writing_style:"locker",emoji_style:"sparsam",sentence_style:"kurz",typical_phrases:["hey du"],forbidden_phrases:["Versprechen"],flirt_style:"respektvoll",sales_rules:"kein Druck",example_messages:["Hey du 😊"],status:"active"};
test("Adult-Character input is bounded and underage personas fail closed",()=>{assert.equal(assertChatAdminCharacterInput(fixture).public_age,24);assert.throws(()=>assertChatAdminCharacterInput({...fixture,public_age:17}),/public_age_must_be_adult/);assert.throws(()=>assertChatAdminCharacterInput({...fixture,provider_token:"secret",public_age:17}),/public_age_must_be_adult/)});
test("context is revision-bound, selected-character-only and inactive/stale data fails closed",()=>{const a={...fixture,id:"a",revision:3};const result=JSON.parse(buildChatAdminCharacterContext(a,"Hallo","Fan 1"));assert.equal(result.character_id,"a");assert.equal(result.character_revision,3);assert.doesNotMatch(JSON.stringify(result),/Sophie|character-b/u);assert.throws(()=>buildChatAdminCharacterContext({...a,status:"inactive"},"Hallo"),/character_unavailable/);assert.throws(()=>buildChatAdminCharacterContext({...a,revision:null},"Hallo"),/character_unavailable/)});
test("controlled schema enforces one workspace, tenant composite keys, adult check, RLS and cascade deletion",async()=>{const sql=await readFile("supabase/controlled/20260920230000_chat_admin_multi_character.sql","utf8");for(const pattern of [/one_chat_admin_workspace_global/u,/public_age between 18 and 99/u,/foreign key\(workspace_id,character_id,conversation_id\)/u,/on delete cascade/u,/enable row level security/u,/granted_to_user_id=auth\.uid\(\)/u,/owner_user_id=auth\.uid\(\)/u])assert.match(sql,pattern);assert.doesNotMatch(sql,/isPlatformAdmin|platform_admin|admin_allowlist/iu)});
test("routes require capability and workspace-bound character; no OnlyFans network, login or auto-send exists",async()=>{const character=await readFile("src/app/api/chatadmin/characters/route.ts","utf8");const reply=await readFile("src/app/api/chatadmin/reply-suggestions/route.ts","utf8");const store=await readFile("src/lib/chatAdmin.ts","utf8");for(const source of [character,reply])assert.match(source,/requireChatAdminCapability/u);assert.match(store,/workspace_id=eq\./u);assert.match(store,/rows\[0\]\.workspace_id!==workspaceId/u);const combined=character+reply+store;assert.doesNotMatch(combined,/onlyfans\.com|OnlyFans API|provider.password|service_role/u);assert.doesNotMatch(combined,/isPlatformAdmin/u)});
test("ChatAdmin stays separate from Platform Admin and UI is capability-hidden",async()=>{const dashboard=await readFile("src/app/dashboard/page.tsx","utf8");const page=await readFile("src/app/chatadmin/page.tsx","utf8");const admin=await readFile("src/lib/admin.ts","utf8");assert.match(dashboard,/showChatAdmin \?/u);assert.match(page,/requireChatAdminCapability/u);assert.match(page,/notFound\(\)/u);assert.doesNotMatch(admin,/chat_admin_multi_character/u);});
test("ChatAdmin cannot inherit user, Admin-CRM, Billing or Operations administration",async()=>{const paths=["src/app/admin/billing/page.tsx","src/app/admin/operations/page.tsx","src/app/api/admin/billing/users/[userId]/crm-access/route.ts"];for(const path of paths){const source=await readFile(path,"utf8");assert.match(source,/isPlatformAdminEmail|requirePlatformAdmin/u,path);assert.doesNotMatch(source,/chat_admin_multi_character|requireChatAdminCapability/u,path);}const root=await readFile("src/app/admin/page.tsx","utf8");assert.match(root,/redirect\("\/admin\/billing"\)/u);const capability=await readFile("src/lib/chatAdmin.ts","utf8");assert.doesNotMatch(capability,/isPlatformAdmin|SUPABASE_SERVICE_ROLE_KEY|impersonat/iu);});
test("account deletion and disclosure enumerate all character datasets",async()=>{const deletion=await readFile("scripts/operations/process-account-deletion.mjs","utf8");const disclosure=await readFile("src/lib/dataDisclosureMetaExport.ts","utf8");for(const table of ["workspace_chat_admin_capabilities","chat_characters","chat_character_conversations","chat_character_messages"]){assert.match(deletion,new RegExp(table,"u"));assert.match(disclosure,new RegExp(table,"u"));}});
